### ISSUE TITLE
Multiple maps with branding error 'appendChild' of null

### ISSUE THREAD

**Issue by nufaylr** [OrdnanceSurvey/os-api-branding#1]
Hi there, we have a use case to have multiple maps on a single page. OS API branding throws an error as configuration options can have a single element. Ideally, os branding function can be a factory or constructor function so we can initialise it multiple times?

Thank you

**Comment by tmnnrs** [comment]
Fixed in https://github.com/OrdnanceSurvey/os-api-branding/commit/0c21e36a508415d6d32d3355cc2a8a89fab83ec6

**Comment by nufaylr** [comment]
Thank you for the prompt fix.

**Comment by davidcblaney** [comment]
Hi, 

This change works for multiple divs with the same ID. Would you be open to using a class name for selection of the map div rather than an ID as the ID's of divs should ideally be unique? 

Another option would be to allow the div parameter in the options to become a css selector string and have '#map' as the default to maintain backwards compatibility.

Happy to open a PR.

Cheers,
David

**Comment by nufaylr** [comment]
Hi @davidcblaney , In my use case, I have multiple maps with different unique Id's so I will be using OS Branding as this example here. 

```
os.Branding.init({ div: 'map-1', logo: 'os-logo-maps-white' });
os.Branding.init({ div: 'map-2', logo: 'os-logo-maps-white' });
```

**Comment by tmnnrs** [comment]
Each of the map div IDs should be unique (as they are what the web mapping libraries will use to instantiate a map object) - so the approach taken by @nufaylr is currently the best way forward.

This should provide users with full control for adding the branding to their maps.

However I will add the option for using a className selector (as an alternative to the div ID) to the backlog.
